let name2 = 20;
let name1 = 4;
console.log('Первое число =' + name2);
console.log('Второй число= ' + name1);
let yigindi = name2 + name1;
console.log('Подвела: ' + yigindi);
let ayirma = name2 - name1;
console.log('Разделение: ' + ayirma);
let kopaytma = name2 * name1;
console.log('Умножение: ' + kopaytma);
let bolinma = name2 / name1;
console.log('Разделять: ' + bolinma);
